name: Build APK (Unsigned)

on:
  workflow_dispatch:

jobs:
  build_app:
    name: 'Build Unsigned APK'
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle*') }}-v1

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Grant Execute Permission to Gradle Wrapper
        run: chmod +x gradlew

      - name: Build APK (Unsigned)
        run: ./gradlew assembleDebug

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-apk
          path: app/build/outputs/apk/debug/app-debug.apk
